version: "3.9"

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: my-backend

    volumes:
      - /app/node_modules
      - ./server:/app
    
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - server-api
  

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - server-api
  

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: amdin123456
    volumes:
      - mongodb-data
    networks:
      - server-api


  client:
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: my-client
    volumes:
      - ./app/node_modules
      - ./client:/app
    depends_on:
      - server
    networks:
      - server-api

  networks:
    server-api:
      driver: bridge
  
  volumes:
    mongo-data:
      driver: local
