FROM node:lts-alpine

LABEL version="1.0"
LABEL description="Development image for my pet project"

WORKDIR /app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]